# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Version stamping
      id: nbgv_version
      uses: dotnet/nbgv@v0.4
      with:
        setAllVars: true
    - name: Set up project list
      id: project-list
      run: |
        projects=$(ls -d */ | grep -v "JackOfAllTrades.AppHost")
        echo "PROJECTS=$projects" >> $GITHUB_OUTPUT

    - name: Publish projects
      run: |

    - name: Install Aspire
      run: dotnet workload install aspire
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish projects
      run: |
        for project in ${{ steps.project-list.outputs.PROJECTS }}
        do
          cd $project
          dotnet publish --os linux --arch x64 -t:PublishContainer /p:ContainerImageTags='"${{ steps.nbgv_version.outputs.Version }};latest"' /p:ContainerRegistry=ghcr.io
          cd ..
        done
      
