# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Updated to 8.0.x based on your error message
    - name: Install Aspire
      run: dotnet workload install aspire
    - name: Install NBGV tool
      run: dotnet tool install -g nbgv

    - name: Set Version
      id: nbgv_version
      run: echo "Version=$(nbgv get-version -v Version)" >> $GITHUB_OUTPUT

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up project list
      id: project-list
      run: |
        projects=$(find . -maxdepth 1 -type d -not -path '*/\.*' -not -path '.' | sed 's|^\./||' | grep -v "JackOfAllTrades.AppHost" | tr '\n' ' ')
        echo "PROJECTS=$projects" >> $GITHUB_OUTPUT

    - name: Publish projects
      run: |
        for project in ${{ steps.project-list.outputs.PROJECTS }}
        do
          if [ -d "$project" ]; then
            echo "Publishing $project"
            cd "$project"
            dotnet publish --os linux --arch x64 -t:PublishContainer \
              /p:ContainerImageTags='"${{ steps.nbgv_version.outputs.Version }};latest"' \
              /p:ContainerRegistry=ghcr.io \
              /p:ContainerRepository=${{ github.repository_owner }}/$project
            cd ..
          else
            echo "Skipping $project as it's not a directory"
          fi
        done



    

